### ISSUE TITLE
Option for returning function already called

### ISSUE THREAD

**Issue by jonricaurte** [johnsoftek/plugin-jade#16]
In my code I always have to call the function for every import I do of a jade file; it would be nice to have an option to pass plugin-jade where it returns the already called function. An Angular 2 example is:

```
import {Component} from 'angular2/core';
import template from './app.component.jade';

@Component({
  selector: 'app',
  template: template()
})
export class AppComponent {
  constructor() { }
}
```

It would be nice if I just had to do this:

```
import {Component} from 'angular2/core';
import template from './app.component.jade';

@Component({
  selector: 'app',
  template: template
})
export class AppComponent {
  constructor() { }
}
```

Without the parens for every template I import. Maybe have an option in the jspm config for this.

Thanks.

**Comment by johnsoftek** [comment]
@jonricaurte The npm page for (server-side) Jade describes the following API:

``` javascript
var jade = require('jade');

// compile 
var fn = jade.compile('string of jade', options);
var html = fn(locals);
```

The jade plugin follows a similar convention. In order to allow bundling jade templates without having to bundle the jade compiler, the plugin invokes the compiler, wraps the resulting javascript function and returns it to the jspm bundler.

So the browser usage is then:

``` javascript
var fn = require('file.jade');
var html = fn(locals);
```

or

``` javascript
import fn from 'file.jade';
let html = fn(locals);
```

Note that this usage allows parameters to be passed to the jade template.

I am uncomfortable changing the standard usage, particularly using a jspm configuration setting.

I propose adding named exports fn and html. Usage:

``` javascript
import { html } from 'component.jade'
```

This would also work:

``` javascript
import fn from 'component.jade'
let template = fn()
```

and this:

``` javascript
import { fn } from 'component.jade'
let template = fn()
```

@jonricaurte What do you think?

**Comment by jonricaurte** [comment]
Sounds good to me. Thanks!
